// Code generated by "spawner -pool=true"; DO NOT EDIT.

package interval

import "sync"

var spawnerPools = map[string]*sync.Pool{
	"interval.LileiSay":     {New: func() interface{} { return spawner["interval.LileiSay"] }},
	"interval.HanMeimeiSay": {New: func() interface{} { return spawner["interval.HanMeimeiSay"] }},
}
