// Code generated by "spawner -pool=true"; DO NOT EDIT.

package msg

import "sync"

var spawnerPools = map[string]*sync.Pool{
	"msg.DrainTest":    {New: func() interface{} { return spawner["msg.DrainTest"]() }},
	"msg.HanMeimeiSay": {New: func() interface{} { return spawner["msg.HanMeimeiSay"]() }},
	"msg.LileiSay":     {New: func() interface{} { return spawner["msg.LileiSay"]() }},
}
